In [2]:
dict1={"Jan":0 ,"Feb":0, "Mar":0,"Apr":0,"May":0,"Jun":0,"Jul":0,"Aug":0,"Sep":0,"Oct":0,"Nov":0,"Dec":0}
print("To exit the loop write anything else than 1 to 12")
while True:
  n=input("Enter birth month in num (1 for jan 2 for feb and so on)")
  if (n=="1"):
    dict1["Jan"]=dict1["Jan"]+1
  elif (n=="2"):
    dict1["Feb"]=dict1["Feb"]+1
  elif (n=="3"):
    dict1["Mar"]=dict1["Mar"]+1
  elif (n=="4"):
    dict1["Apr"]=dict1["Apr"]+1
  elif (n=="5"):
    dict1["May"]=dict1["May"]+1
  elif (n=="6"):
    dict1["Jun"]=dict1["Jun"]+1
  elif (n=="7"):
    dict1["Jul"]=dict1["Jul"]+1
  elif (n=="8"):
    dict1["Aug"]=dict1["Aug"]+1
  elif (n=="9"):
    dict1["Sep"]=dict1["Sep"]+1
  elif (n=="10"):
    dict1["Oct"]=dict1["Oct"]+1
  elif (n=="11"):
    dict1["Nov"]=dict1["Nov"]+1
  elif (n=="12"):
    dict1["Dec"]=dict1["Dec"]+1
  else:
    break;
print(dict1)
v=list(dict1.values())
k=list(dict1.keys())
 
print("Maximum birthday is in:",k[v.index(max(v))])
print("Minimum birthday is in:",k[v.index(min(v))])

To exit the loop write anything else than 1 to 12
Enter birth month in num (1 for jan 2 for feb and so on)6
Enter birth month in num (1 for jan 2 for feb and so on)6
Enter birth month in num (1 for jan 2 for feb and so on)4
Enter birth month in num (1 for jan 2 for feb and so on)4
Enter birth month in num (1 for jan 2 for feb and so on)9
Enter birth month in num (1 for jan 2 for feb and so on)10
Enter birth month in num (1 for jan 2 for feb and so on)12
Enter birth month in num (1 for jan 2 for feb and so on)2
Enter birth month in num (1 for jan 2 for feb and so on)3
Enter birth month in num (1 for jan 2 for feb and so on)11
Enter birth month in num (1 for jan 2 for feb and so on)5
Enter birth month in num (1 for jan 2 for feb and so on)10
Enter birth month in num (1 for jan 2 for feb and so on)4
Enter birth month in num (1 for jan 2 for feb and so on)8
Enter birth month in num (1 for jan 2 for feb and so on)12
Enter birth month in num (1 for jan 2 for feb and so on)4
Enter birth month in num (1 for jan 2 for feb and so on)6
Enter birth month in num (1 for jan 2 for feb and so on)11
Enter birth month in num (1 for jan 2 for feb and so on)10
Enter birth month in num (1 for jan 2 for feb and so on)7
Enter birth month in num (1 for jan 2 for feb and so on)9
Enter birth month in num (1 for jan 2 for feb and so on)5
Enter birth month in num (1 for jan 2 for feb and so on)11
Enter birth month in num (1 for jan 2 for feb and so on)1
Enter birth month in num (1 for jan 2 for feb and so on)4
Enter birth month in num (1 for jan 2 for feb and so on)6
Enter birth month in num (1 for jan 2 for feb and so on)5
Enter birth month in num (1 for jan 2 for feb and so on)9
Enter birth month in num (1 for jan 2 for feb and so on)7
Enter birth month in num (1 for jan 2 for feb and so on)12
Enter birth month in num (1 for jan 2 for feb and so on)8
Enter birth month in num (1 for jan 2 for feb and so on)7
Enter birth month in num (1 for jan 2 for feb and so on)8
Enter birth month in num (1 for jan 2 for feb and so on)13
{'Jan': 1, 'Feb': 1, 'Mar': 1, 'Apr': 5, 'May': 3, 'Jun': 4, 'Jul': 3, 'Aug': 3, 'Sep': 3, 'Oct': 3, 'Nov': 3, 'Dec': 3}
Maximum birthday is in: Apr
Minimum birthday is in: Jan